/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.fcg

import com.fcg.authentication.JwtConfig
import com.fcg.plugins.*
import io.ktor.server.application.*

class App {}

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

val jwtConfig = JwtConfig(System.getenv("KTOR_CGD_JWT_SECRET"))

fun Application.module() {
    configureHTTP()
    configureSerialization()
    configureDatabases()
    configureRouting()
    configureSecurity()
}
