/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.fcg

import com.fcg.plugins.configureDatabases
import com.fcg.plugins.configureHTTP
import com.fcg.plugins.configureRouting
import com.fcg.plugins.configureSerialization
import io.ktor.server.application.*

class App {}

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    configureHTTP()
    configureSerialization()
    configureDatabases()
    configureRouting()
}
